### ISSUE TITLE
Move OpenTraffic from Potential to Current Standard

### ISSUE THREAD

**Issue by rcheetham** [azavea/open-data-standards#12]
Re-write text
Add federal items to other resources
Add info on private companies and World Bank effort

**Comment by danford1** [comment]
@rcheetham I moved the Traffic Monitoring and Volume standard from Future Potential Standards to Existing Standards:
`standards/future_standards/built_environment/traffic_monitoring_and_volume.md`
to...
`standards/domain_specific_standards/traffic_monitoring_and_volume.md`

I also updated the format of the file to match that of Existing Standards. The text still requires editing.

**Comment by danford1** [comment]
Renamed to `OpenTraffic.md`

**Comment by danford1** [comment]
Added OpenTraffic as a current open data standard. @rcheetham reviewed and edited.
