### ISSUE TITLE
Add a license to the book

### ISSUE THREAD

**Issue by danford1** [azavea/open-data-standards#3]
Potential example for Creative Commons:
https://github.com/opendata/How-To/blob/master/LICENSE

**Comment by rcheetham** [comment]
good call on license. I would like to go with CC-BY-SA
https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/#sa

**Comment by rcheetham** [comment]
I set the license in GitBook as CC-BY-SA 4.0 International
https://www.gitbook.com/book/azavea/open-data-standards/settings

**Comment by rcheetham** [comment]
I added a note on the intro page about CC-BY-SA as well as the Contribute page. I generated the text using the license chooser https://creativecommons.org/choose/
